import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./src/**/*.{ts,tsx,js,jsx,mdx}"],
  theme: {
    extend: {
      colors: {
        "inverse-on-surface": "#f1f0f5",
        secondary: "#405e96",
        "on-secondary-container": "#2d4c83",
        tertiary: "#9e3d00",
        "tertiary-container": "#c64f00",
        "on-primary-fixed-variant": "#004493",
        "on-error-container": "#93000a",
        "surface-variant": "#e3e2e7",
        "surface-tint": "#005bc1",
        "on-primary-container": "#fefcff",
        "surface-container": "#eeedf3",
        "on-secondary-fixed": "#001a41",
        "primary-fixed-dim": "#adc6ff",
        "primary-container": "#0070eb",
        error: "#ba1a1a",
        background: "#faf9fe",
        "on-tertiary": "#ffffff",
        "secondary-fixed": "#d8e2ff",
        "primary-fixed": "#d8e2ff",
        "on-background": "#1a1b1f",
        surface: "#faf9fe",
        "on-secondary-fixed-variant": "#26467d",
        "on-primary": "#ffffff",
        "surface-container-highest": "#e3e2e7",
        "on-tertiary-container": "#fffbff",
        "on-error": "#ffffff",
        "surface-dim": "#dad9df",
        "on-secondary": "#ffffff",
        "surface-container-low": "#f4f3f8",
        primary: "#0058bc",
        outline: "#717786",
        "surface-bright": "#faf9fe",
        "surface-container-lowest": "#ffffff",
        "error-container": "#ffdad6",
        "on-surface-variant": "#414755",
        "surface-container-high": "#e9e7ed",
        "outline-variant": "#c1c6d7",
        "tertiary-fixed-dim": "#ffb595",
        "secondary-container": "#a1befd",
        "inverse-surface": "#2f3034",
        "tertiary-fixed": "#ffdbcc",
        "on-tertiary-fixed": "#351000",
        "inverse-primary": "#adc6ff",
        "on-primary-fixed": "#001a41",
        "secondary-fixed-dim": "#adc6ff",
        "on-tertiary-fixed-variant": "#7c2e00",
        "on-surface": "#1a1b1f",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "-apple-system", "sans-serif"],
        headline: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      boxShadow: {
        ambient: "0 8px 24px rgba(26,27,31,0.06)",
        "ambient-xl": "0 8px 24px rgba(26,27,31,0.08)",
        "primary-glow": "0 8px 24px rgba(0,88,188,0.2)",
        "ambient-up": "0 -8px 24px rgba(26,27,31,0.04)",
      },
      backgroundImage: {
        "primary-gradient": "linear-gradient(135deg, #0058bc 0%, #0070eb 100%)",
      },
    },
  },
  plugins: [],
};

export default config;
