import type { Config } from "tailwindcss";

const v = (name: string) => `var(--color-${name})`;

const config: Config = {
  darkMode: "class",
  content: ["./src/**/*.{ts,tsx,js,jsx,mdx}"],
  theme: {
    extend: {
      colors: {
        surface: v("surface"),
        "surface-dim": v("surface-dim"),
        "surface-bright": v("surface-bright"),
        "surface-container-lowest": v("surface-container-lowest"),
        "surface-container-low": v("surface-container-low"),
        "surface-container": v("surface-container"),
        "surface-container-high": v("surface-container-high"),
        "surface-container-highest": v("surface-container-highest"),
        "surface-variant": v("surface-variant"),
        "surface-tint": v("surface-tint"),
        "on-surface": v("on-surface"),
        "on-surface-variant": v("on-surface-variant"),
        "inverse-surface": v("inverse-surface"),
        "inverse-on-surface": v("inverse-on-surface"),
        background: v("background"),
        "on-background": v("on-background"),
        primary: v("primary"),
        "on-primary": v("on-primary"),
        "primary-container": v("primary-container"),
        "on-primary-container": v("on-primary-container"),
        "primary-fixed": v("primary-fixed"),
        "primary-fixed-dim": v("primary-fixed-dim"),
        "on-primary-fixed": v("on-primary-fixed"),
        "on-primary-fixed-variant": v("on-primary-fixed-variant"),
        "inverse-primary": v("inverse-primary"),
        secondary: v("secondary"),
        "on-secondary": v("on-secondary"),
        "secondary-container": v("secondary-container"),
        "on-secondary-container": v("on-secondary-container"),
        "secondary-fixed": v("secondary-fixed"),
        "secondary-fixed-dim": v("secondary-fixed-dim"),
        "on-secondary-fixed": v("on-secondary-fixed"),
        "on-secondary-fixed-variant": v("on-secondary-fixed-variant"),
        tertiary: v("tertiary"),
        "on-tertiary": v("on-tertiary"),
        "tertiary-container": v("tertiary-container"),
        "on-tertiary-container": v("on-tertiary-container"),
        "tertiary-fixed": v("tertiary-fixed"),
        "tertiary-fixed-dim": v("tertiary-fixed-dim"),
        "on-tertiary-fixed": v("on-tertiary-fixed"),
        "on-tertiary-fixed-variant": v("on-tertiary-fixed-variant"),
        error: v("error"),
        "on-error": v("on-error"),
        "error-container": v("error-container"),
        "on-error-container": v("on-error-container"),
        outline: v("outline"),
        "outline-variant": v("outline-variant"),
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "-apple-system", "sans-serif"],
        headline: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      boxShadow: {
        ambient: "0 8px 24px rgba(26,27,31,0.06)",
        "ambient-xl": "0 8px 24px rgba(26,27,31,0.08)",
        "primary-glow": "0 8px 24px rgba(0,88,188,0.2)",
        "ambient-up": "0 -8px 24px rgba(26,27,31,0.04)",
      },
      backgroundImage: {
        "primary-gradient": "var(--gradient-primary)",
      },
    },
  },
  plugins: [],
};

export default config;
